### ISSUE TITLE
Not able to fetch the price

### ISSUE THREAD

**Issue by venkateshpamarthi** [smartcontractkit/solana-starter-kit#18]
logs: [
    'Program 7R6ZpXj8WcStMFcQ3MwevwLWyc1BbzjQbC57esGCHgW3 invoke [1]',
    'Program log: Instruction: Execute',
    'Program 7R6ZpXj8WcStMFcQ3MwevwLWyc1BbzjQbC57esGCHgW3 consumed 4227 of 200000 compute units',
    'Program 7R6ZpXj8WcStMFcQ3MwevwLWyc1BbzjQbC57esGCHgW3 failed: Instruction passed to inner instruction is too large (12884933988 > 1280)'
  ],

**Comment by QingyangKong** [comment]
The anchor version was updated last week, the issue should resolved.
